[package]
name = "simplecl"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A simple command-line tool"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
ocl = "0.19"
plotters = "0.3"